#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -cp 'jars/*' -Djava.security.manager -Djava.security.policy=policies/dcvm.policy fr.upmc.components.examples.basic_cs.DistributedCVM $1 config.xml
